# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'TerpMarketplace' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TerpMarketplace
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'MessageKit', '2.0.0'
  pod 'MessageInputBar'
 end
